name: Automerge Pull Request

on:
  schedule:
    # You can setup schedule here
    - cron: '*/2 * * * *'

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://pnsj-jangid:${{secrets.GITHUB_TOKEN}}@github.com/pnsj-jangid/auto-marge-action-test-app.git


  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: develop

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/pnsj-jangid/auto-marge-action-test-app.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

  RETS_IMPORT_BRANCH: rets-import

jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
    - name: Merge develop into main branch
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MASTER_BRANCH}} tmp
        cd tmp
        git config user.name "PNSJ JANGID "
        git config user.email "pnsj.jangid@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MY_BRANCH}}
        git push

  merge-rets-import:
    runs-on: ubuntu-latest

    steps:
    - name: Merge develop into rets-import branch
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.RETS_IMPORT_BRANCH}} tmp
        cd tmp
        git config user.name "PNSJ JANGID "
        git config user.email "pnsj.jangid@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MY_BRANCH}}
        git push
