name: Automerge

on:
  # Try enabling auto-merge for all open pull requests. (Only recommended for testing.)
  push:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          BASE_BRANCHES: "main"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true