name: Make PR
on:
  push:
    branches:
      - develop
jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Auto PR created"
          branch: main