name: Create develop pull request
on:
  push:
    branches:
      - develop
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: develop
  notify:
    needs: job1
    automerge:
      runs-on: ubuntu-latest
      steps:
        - id: automerge
          name: automerge
          uses: "pascalgn/automerge-action@v0.15.5"
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            BASE_BRANCHES: "main"
            MERGE_LABELS: ""

